// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AggregatedPoint struct {
	Time  time.Time `json:"time"`
	Value float64   `json:"value"`
	Count int       `json:"count"`
}

type AggregationInput struct {
	Interval string      `json:"interval"`
	Function AggFunction `json:"function"`
}

type DataPoint struct {
	Time  time.Time `json:"time"`
	Value float64   `json:"value"`
}

type LabelEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type LabelFilter struct {
	Expression string `json:"expression"`
}

type Labels struct {
	Keys    []string      `json:"keys"`
	Value   *string       `json:"value,omitempty"`
	Entries []*LabelEntry `json:"entries"`
}

type Query struct {
}

type Series struct {
	Meta             *SeriesMeta        `json:"meta"`
	Points           []*DataPoint       `json:"points"`
	AggregatedPoints []*AggregatedPoint `json:"aggregatedPoints"`
	Statistics       *SeriesStatistics  `json:"statistics,omitempty"`
}

type SeriesMeta struct {
	ID         string    `json:"id"`
	Endpoint   string    `json:"endpoint"`
	Metric     string    `json:"metric"`
	Labels     *Labels   `json:"labels"`
	LabelsHash string    `json:"labelsHash"`
	CreatedAt  time.Time `json:"createdAt"`
}

type SeriesStatistics struct {
	Min   float64 `json:"min"`
	Max   float64 `json:"max"`
	Avg   float64 `json:"avg"`
	Sum   float64 `json:"sum"`
	Count int     `json:"count"`
}

type TimeRangeInput struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type AggFunction string

const (
	AggFunctionAvg   AggFunction = "AVG"
	AggFunctionMin   AggFunction = "MIN"
	AggFunctionMax   AggFunction = "MAX"
	AggFunctionSum   AggFunction = "SUM"
	AggFunctionCount AggFunction = "COUNT"
)

var AllAggFunction = []AggFunction{
	AggFunctionAvg,
	AggFunctionMin,
	AggFunctionMax,
	AggFunctionSum,
	AggFunctionCount,
}

func (e AggFunction) IsValid() bool {
	switch e {
	case AggFunctionAvg, AggFunctionMin, AggFunctionMax, AggFunctionSum, AggFunctionCount:
		return true
	}
	return false
}

func (e AggFunction) String() string {
	return string(e)
}

func (e *AggFunction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AggFunction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AggFunction", str)
	}
	return nil
}

func (e AggFunction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AggFunction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AggFunction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
