package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/db-cockpit/pkg/domain/dataquery"
)

// Endpoints is the resolver for the endpoints field.
func (r *queryResolver) Endpoints(ctx context.Context) ([]string, error) {
	return r.service.GetEndpoints(ctx)
}

// Metrics is the resolver for the metrics field.
func (r *queryResolver) Metrics(ctx context.Context, endpoint string) ([]string, error) {
	return r.service.GetMetrics(ctx, endpoint)
}

// Series is the resolver for the series field.
func (r *queryResolver) Series(ctx context.Context, endpoint *string, metric *string, labels *LabelFilter, timeRange TimeRangeInput, limit *int) ([]*Series, error) {
	req := &dataquery.SeriesQuery{
		TimeRange: parseTimeRange(timeRange),
	}
	if endpoint != nil {
		req.Endpoint = *endpoint
	}
	if metric != nil {
		req.Metric = *metric
	}
	if labels != nil {
		req.LabelFilter = labels.Expression
	}
	if limit != nil {
		req.Limit = *limit
	}

	series, err := r.service.QuerySeries(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to query series: %w", err)
	}

	return toSeriesList(series), nil
}

// SeriesByID is the resolver for the seriesById field.
func (r *queryResolver) SeriesByID(ctx context.Context, id string, timeRange TimeRangeInput) (*Series, error) {
	seriesID, err := parseID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid series ID: %w", err)
	}

	tr := parseTimeRange(timeRange)
	sd, err := r.service.GetSeriesByID(ctx, seriesID, &tr)
	if err != nil {
		return nil, fmt.Errorf("failed to get series: %w", err)
	}

	return toSeries(sd), nil
}

// SeriesMulti is the resolver for the seriesMulti field.
func (r *queryResolver) SeriesMulti(ctx context.Context, endpoints []string, metrics []string, labels *LabelFilter, timeRange TimeRangeInput, aggregation *AggregationInput) ([]*Series, error) {
	req := &dataquery.MultiSeriesQuery{
		Endpoints: endpoints,
		Metrics:   metrics,
		TimeRange: parseTimeRange(timeRange),
	}
	if labels != nil {
		req.LabelFilter = labels.Expression
	}
	if aggregation != nil {
		req.Aggregation = &dataquery.Aggregation{
			Interval: aggregation.Interval,
			Function: parseAggFunction(aggregation.Function),
		}
	}

	series, err := r.service.QuerySeriesMulti(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to query series: %w", err)
	}

	return toSeriesList(series), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
