// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/agent/agent.proto

package agent

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ExecutionAgentServiceClient is the client API for ExecutionAgentService service.
type ExecutionAgentServiceClient interface {
	ExecuteSQL(ctx context.Context, in *ExecuteSQLRequest, opts ...grpc.CallOption) (*ExecuteSQLResponse, error)
	ExecuteTransaction(ctx context.Context, in *ExecuteTransactionRequest, opts ...grpc.CallOption) (*ExecuteTransactionResponse, error)
	ExecuteAPICall(ctx context.Context, in *ExecuteAPICallRequest, opts ...grpc.CallOption) (*ExecuteAPICallResponse, error)
	GetExecutionStatus(ctx context.Context, in *GetExecutionStatusRequest, opts ...grpc.CallOption) (*GetExecutionStatusResponse, error)
	CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*CancelExecutionResponse, error)
	GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*GetAuditLogResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type executionAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionAgentServiceClient(cc grpc.ClientConnInterface) ExecutionAgentServiceClient {
	return &executionAgentServiceClient{cc}
}

func (c *executionAgentServiceClient) ExecuteSQL(ctx context.Context, in *ExecuteSQLRequest, opts ...grpc.CallOption) (*ExecuteSQLResponse, error) {
	out := new(ExecuteSQLResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.ExecutionAgentService/ExecuteSQL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionAgentServiceClient) ExecuteTransaction(ctx context.Context, in *ExecuteTransactionRequest, opts ...grpc.CallOption) (*ExecuteTransactionResponse, error) {
	out := new(ExecuteTransactionResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.ExecutionAgentService/ExecuteTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionAgentServiceClient) ExecuteAPICall(ctx context.Context, in *ExecuteAPICallRequest, opts ...grpc.CallOption) (*ExecuteAPICallResponse, error) {
	out := new(ExecuteAPICallResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.ExecutionAgentService/ExecuteAPICall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionAgentServiceClient) GetExecutionStatus(ctx context.Context, in *GetExecutionStatusRequest, opts ...grpc.CallOption) (*GetExecutionStatusResponse, error) {
	out := new(GetExecutionStatusResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.ExecutionAgentService/GetExecutionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionAgentServiceClient) CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*CancelExecutionResponse, error) {
	out := new(CancelExecutionResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.ExecutionAgentService/CancelExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionAgentServiceClient) GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*GetAuditLogResponse, error) {
	out := new(GetAuditLogResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.ExecutionAgentService/GetAuditLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionAgentServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.ExecutionAgentService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionAgentServiceServer is the server API for ExecutionAgentService service.
type ExecutionAgentServiceServer interface {
	ExecuteSQL(context.Context, *ExecuteSQLRequest) (*ExecuteSQLResponse, error)
	ExecuteTransaction(context.Context, *ExecuteTransactionRequest) (*ExecuteTransactionResponse, error)
	ExecuteAPICall(context.Context, *ExecuteAPICallRequest) (*ExecuteAPICallResponse, error)
	GetExecutionStatus(context.Context, *GetExecutionStatusRequest) (*GetExecutionStatusResponse, error)
	CancelExecution(context.Context, *CancelExecutionRequest) (*CancelExecutionResponse, error)
	GetAuditLog(context.Context, *GetAuditLogRequest) (*GetAuditLogResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
}

func RegisterExecutionAgentServiceServer(s grpc.ServiceRegistrar, srv ExecutionAgentServiceServer) {
	s.RegisterService(&ExecutionAgentService_ServiceDesc, srv)
}

func _ExecutionAgentService_ExecuteSQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionAgentServiceServer).ExecuteSQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.ExecutionAgentService/ExecuteSQL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionAgentServiceServer).ExecuteSQL(ctx, req.(*ExecuteSQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var ExecutionAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.ExecutionAgentService",
	HandlerType: (*ExecutionAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteSQL",
			Handler:    _ExecutionAgentService_ExecuteSQL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/agent/agent.proto",
}

// ExecuteSQLRequest message
type ExecuteSQLRequest struct {
	ExecutionId   string           `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TenantId      string           `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string           `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DatabaseId    string           `protobuf:"bytes,4,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	DatabaseType  string           `protobuf:"bytes,5,opt,name=database_type,json=databaseType,proto3" json:"database_type,omitempty"`
	Sql           string           `protobuf:"bytes,6,opt,name=sql,proto3" json:"sql,omitempty"`
	Parameters    []*SQLParameter  `protobuf:"bytes,7,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Options       *ExecutionOptions `protobuf:"bytes,8,opt,name=options,proto3" json:"options,omitempty"`
	AuditInfo     *AuditInfo       `protobuf:"bytes,9,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
}

func (x *ExecuteSQLRequest) Reset()         { *x = ExecuteSQLRequest{} }
func (x *ExecuteSQLRequest) String() string { return "ExecuteSQLRequest" }
func (x *ExecuteSQLRequest) ProtoMessage()  {}

type SQLParameter struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SQLParameter) Reset()         { *x = SQLParameter{} }
func (x *SQLParameter) String() string { return "SQLParameter" }
func (x *SQLParameter) ProtoMessage()  {}

type ExecutionOptions struct {
	TimeoutSeconds  int32  `protobuf:"varint,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	MaxRows         int32  `protobuf:"varint,2,opt,name=max_rows,json=maxRows,proto3" json:"max_rows,omitempty"`
	ReadOnly        bool   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	ExplainOnly     bool   `protobuf:"varint,4,opt,name=explain_only,json=explainOnly,proto3" json:"explain_only,omitempty"`
	IsolationLevel  string `protobuf:"bytes,5,opt,name=isolation_level,json=isolationLevel,proto3" json:"isolation_level,omitempty"`
}

func (x *ExecutionOptions) Reset()         { *x = ExecutionOptions{} }
func (x *ExecutionOptions) String() string { return "ExecutionOptions" }
func (x *ExecutionOptions) ProtoMessage()  {}

type AuditInfo struct {
	Source  string            `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Reason  string            `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Context map[string]string `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty"`
}

func (x *AuditInfo) Reset()         { *x = AuditInfo{} }
func (x *AuditInfo) String() string { return "AuditInfo" }
func (x *AuditInfo) ProtoMessage()  {}

type ExecuteSQLResponse struct {
	ExecutionId     string          `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status          ExecutionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=agent.v1.ExecutionStatus" json:"status,omitempty"`
	Columns         []*ResultColumn `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows            []*ResultRow    `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows,omitempty"`
	RowsAffected    int64           `protobuf:"varint,5,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	RowsReturned    int64           `protobuf:"varint,6,opt,name=rows_returned,json=rowsReturned,proto3" json:"rows_returned,omitempty"`
	ExecutionTimeMs int64           `protobuf:"varint,7,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	ErrorMessage    string          `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AuditId         string          `protobuf:"bytes,9,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	Plan            *ExecutionPlan  `protobuf:"bytes,10,opt,name=plan,proto3" json:"plan,omitempty"`
}

func (x *ExecuteSQLResponse) Reset()         { *x = ExecuteSQLResponse{} }
func (x *ExecuteSQLResponse) String() string { return "ExecuteSQLResponse" }
func (x *ExecuteSQLResponse) ProtoMessage()  {}

type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_PENDING     ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_RUNNING     ExecutionStatus = 2
	ExecutionStatus_EXECUTION_STATUS_COMPLETED   ExecutionStatus = 3
	ExecutionStatus_EXECUTION_STATUS_FAILED      ExecutionStatus = 4
	ExecutionStatus_EXECUTION_STATUS_CANCELLED   ExecutionStatus = 5
	ExecutionStatus_EXECUTION_STATUS_TIMEOUT     ExecutionStatus = 6
)

type ResultColumn struct {
	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Nullable bool   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
}

func (x *ResultColumn) Reset()         { *x = ResultColumn{} }
func (x *ResultColumn) String() string { return "ResultColumn" }
func (x *ResultColumn) ProtoMessage()  {}

type ResultRow struct {
	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *ResultRow) Reset()         { *x = ResultRow{} }
func (x *ResultRow) String() string { return "ResultRow" }
func (x *ResultRow) ProtoMessage()  {}

type ExecutionPlan struct {
	PlanText      string   `protobuf:"bytes,1,opt,name=plan_text,json=planText,proto3" json:"plan_text,omitempty"`
	EstimatedCost float64  `protobuf:"fixed64,2,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	EstimatedRows float64  `protobuf:"fixed64,3,opt,name=estimated_rows,json=estimatedRows,proto3" json:"estimated_rows,omitempty"`
	Warnings      []string `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
}

func (x *ExecutionPlan) Reset()         { *x = ExecutionPlan{} }
func (x *ExecutionPlan) String() string { return "ExecutionPlan" }
func (x *ExecutionPlan) ProtoMessage()  {}

type ExecuteTransactionRequest struct {
	TransactionId string            `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TenantId      string            `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string            `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DatabaseId    string            `protobuf:"bytes,4,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	Statements    []*SQLStatement   `protobuf:"bytes,5,rep,name=statements,proto3" json:"statements,omitempty"`
	Options       *TransactionOptions `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	AuditInfo     *AuditInfo        `protobuf:"bytes,7,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
}

func (x *ExecuteTransactionRequest) Reset()         { *x = ExecuteTransactionRequest{} }
func (x *ExecuteTransactionRequest) String() string { return "ExecuteTransactionRequest" }
func (x *ExecuteTransactionRequest) ProtoMessage()  {}

type SQLStatement struct {
	Sql        string          `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Parameters []*SQLParameter `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
}

func (x *SQLStatement) Reset()         { *x = SQLStatement{} }
func (x *SQLStatement) String() string { return "SQLStatement" }
func (x *SQLStatement) ProtoMessage()  {}

type TransactionOptions struct {
	TimeoutSeconds  int32  `protobuf:"varint,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	IsolationLevel  string `protobuf:"bytes,2,opt,name=isolation_level,json=isolationLevel,proto3" json:"isolation_level,omitempty"`
	RetryOnDeadlock bool   `protobuf:"varint,3,opt,name=retry_on_deadlock,json=retryOnDeadlock,proto3" json:"retry_on_deadlock,omitempty"`
	MaxRetries      int32  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
}

func (x *TransactionOptions) Reset()         { *x = TransactionOptions{} }
func (x *TransactionOptions) String() string { return "TransactionOptions" }
func (x *TransactionOptions) ProtoMessage()  {}

type ExecuteTransactionResponse struct {
	TransactionId string            `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        ExecutionStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=agent.v1.ExecutionStatus" json:"status,omitempty"`
	Results       []*StatementResult `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	TotalTimeMs   int64             `protobuf:"varint,4,opt,name=total_time_ms,json=totalTimeMs,proto3" json:"total_time_ms,omitempty"`
	ErrorMessage  string            `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AuditId       string            `protobuf:"bytes,6,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
}

func (x *ExecuteTransactionResponse) Reset()         { *x = ExecuteTransactionResponse{} }
func (x *ExecuteTransactionResponse) String() string { return "ExecuteTransactionResponse" }
func (x *ExecuteTransactionResponse) ProtoMessage()  {}

type StatementResult struct {
	StatementIndex  int32           `protobuf:"varint,1,opt,name=statement_index,json=statementIndex,proto3" json:"statement_index,omitempty"`
	Success         bool            `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	RowsAffected    int64           `protobuf:"varint,3,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	Columns         []*ResultColumn `protobuf:"bytes,4,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows            []*ResultRow    `protobuf:"bytes,5,rep,name=rows,proto3" json:"rows,omitempty"`
	ExecutionTimeMs int64           `protobuf:"varint,6,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	Error           string          `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *StatementResult) Reset()         { *x = StatementResult{} }
func (x *StatementResult) String() string { return "StatementResult" }
func (x *StatementResult) ProtoMessage()  {}

type ExecuteAPICallRequest struct {
	CallId     string       `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	TenantId   string       `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId     string       `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Endpoint   *APIEndpoint `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Request    *HTTPRequest `protobuf:"bytes,5,opt,name=request,proto3" json:"request,omitempty"`
	AuditInfo  *AuditInfo   `protobuf:"bytes,6,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
}

func (x *ExecuteAPICallRequest) Reset()         { *x = ExecuteAPICallRequest{} }
func (x *ExecuteAPICallRequest) String() string { return "ExecuteAPICallRequest" }
func (x *ExecuteAPICallRequest) ProtoMessage()  {}

type APIEndpoint struct {
	Name           string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url            string            `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method         string            `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Headers        map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	TimeoutSeconds int32             `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
}

func (x *APIEndpoint) Reset()         { *x = APIEndpoint{} }
func (x *APIEndpoint) String() string { return "APIEndpoint" }
func (x *APIEndpoint) ProtoMessage()  {}

type HTTPRequest struct {
	Path        string            `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	QueryParams map[string]string `protobuf:"bytes,2,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty"`
	Headers     map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body        []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *HTTPRequest) Reset()         { *x = HTTPRequest{} }
func (x *HTTPRequest) String() string { return "HTTPRequest" }
func (x *HTTPRequest) ProtoMessage()  {}

type ExecuteAPICallResponse struct {
	CallId          string            `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Status          ExecutionStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=agent.v1.ExecutionStatus" json:"status,omitempty"`
	StatusCode      int32             `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers         map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	Body            []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	ExecutionTimeMs int64             `protobuf:"varint,6,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	ErrorMessage    string            `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AuditId         string            `protobuf:"bytes,8,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
}

func (x *ExecuteAPICallResponse) Reset()         { *x = ExecuteAPICallResponse{} }
func (x *ExecuteAPICallResponse) String() string { return "ExecuteAPICallResponse" }
func (x *ExecuteAPICallResponse) ProtoMessage()  {}

type GetExecutionStatusRequest struct {
	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
}

func (x *GetExecutionStatusRequest) Reset()         { *x = GetExecutionStatusRequest{} }
func (x *GetExecutionStatusRequest) String() string { return "GetExecutionStatusRequest" }
func (x *GetExecutionStatusRequest) ProtoMessage()  {}

type GetExecutionStatusResponse struct {
	ExecutionId      string          `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status           ExecutionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=agent.v1.ExecutionStatus" json:"status,omitempty"`
	ProgressPercent  int32           `protobuf:"varint,3,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	CurrentOperation string          `protobuf:"bytes,4,opt,name=current_operation,json=currentOperation,proto3" json:"current_operation,omitempty"`
	StartedAt        int64           `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ElapsedMs        int64           `protobuf:"varint,6,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	ErrorMessage     string          `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *GetExecutionStatusResponse) Reset()         { *x = GetExecutionStatusResponse{} }
func (x *GetExecutionStatusResponse) String() string { return "GetExecutionStatusResponse" }
func (x *GetExecutionStatusResponse) ProtoMessage()  {}

type CancelExecutionRequest struct {
	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Reason      string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *CancelExecutionRequest) Reset()         { *x = CancelExecutionRequest{} }
func (x *CancelExecutionRequest) String() string { return "CancelExecutionRequest" }
func (x *CancelExecutionRequest) ProtoMessage()  {}

type CancelExecutionResponse struct {
	Success     bool            `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExecutionId string          `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status      ExecutionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=agent.v1.ExecutionStatus" json:"status,omitempty"`
	Message     string          `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CancelExecutionResponse) Reset()         { *x = CancelExecutionResponse{} }
func (x *CancelExecutionResponse) String() string { return "CancelExecutionResponse" }
func (x *CancelExecutionResponse) ProtoMessage()  {}

type GetAuditLogRequest struct {
	TenantId     string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ExecutionId  string `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	UserId       string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime    int64  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime      int64  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit        int32  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset       int32  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetAuditLogRequest) Reset()         { *x = GetAuditLogRequest{} }
func (x *GetAuditLogRequest) String() string { return "GetAuditLogRequest" }
func (x *GetAuditLogRequest) ProtoMessage()  {}

type GetAuditLogResponse struct {
	Entries []*AuditEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total   int32         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetAuditLogResponse) Reset()         { *x = GetAuditLogResponse{} }
func (x *GetAuditLogResponse) String() string { return "GetAuditLogResponse" }
func (x *GetAuditLogResponse) ProtoMessage()  {}

type AuditEntry struct {
	AuditId         string            `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	ExecutionId     string            `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TenantId        string            `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId          string            `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DatabaseId      string            `protobuf:"bytes,5,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	OperationType   string            `protobuf:"bytes,6,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	OperationDetail string            `protobuf:"bytes,7,opt,name=operation_detail,json=operationDetail,proto3" json:"operation_detail,omitempty"`
	Status          ExecutionStatus   `protobuf:"varint,8,opt,name=status,proto3,enum=agent.v1.ExecutionStatus" json:"status,omitempty"`
	RowsAffected    int64             `protobuf:"varint,9,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	ExecutionTimeMs int64             `protobuf:"varint,10,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	Timestamp       int64             `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source          string            `protobuf:"bytes,12,opt,name=source,proto3" json:"source,omitempty"`
	Context         map[string]string `protobuf:"bytes,13,rep,name=context,proto3" json:"context,omitempty"`
}

func (x *AuditEntry) Reset()         { *x = AuditEntry{} }
func (x *AuditEntry) String() string { return "AuditEntry" }
func (x *AuditEntry) ProtoMessage()  {}

type HealthRequest struct{}

func (x *HealthRequest) Reset()         { *x = HealthRequest{} }
func (x *HealthRequest) String() string { return "HealthRequest" }
func (x *HealthRequest) ProtoMessage()  {}

type HealthResponse struct {
	Status     string            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp  int64             `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Connections map[string]string `protobuf:"bytes,3,rep,name=connections,proto3" json:"connections,omitempty"`
}

func (x *HealthResponse) Reset()         { *x = HealthResponse{} }
func (x *HealthResponse) String() string { return "HealthResponse" }
func (x *HealthResponse) ProtoMessage()  {}

func (s *ExecutionStatus) Error() string {
	return status.Error(codes.Unknown, "execution status error").Error()
}